export const fruitLabels = {
  almond: "Almond",
  apple: "Apple",
  apricot: "Apricot",
  cherry: "Cherry",
  crabapple: "Crab Apple",
  elderberry: "Elderberry",
  europeanbeech: "European Beech",
  hazel: "Hazel",
  honeylocust: "Honey Locust",
  juniper: "Juniper",
  loquat: "Loquat",
  mulberry: "Mulberry",
  olive: "Olive",
  peach: "Peach",
  pear: "Pear",
  persimmon: "Persimmon",
  plum: "Plum",
  quince: "Quince",
  serviceberry: "Service Berry",
  strawberry: "Strawberry Tree",
  sweetbay: "Sweet Bay",
  sweetchestnut: "Sweet Chestnut",
  walnut: "Walnut",
};
